# coding: utf-8

User.create!(guardian: "sample",guardiankana:"サンプル",email: "sample@email.com",password: "password",password_confirmation: "password",admin: true)
User.create!(guardian:"山田太郎",guardiankana:"ヤマダタロウ",email:"sample-1@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"木村喜朗",guardiankana:"キムラヨシロウ",email:"sample-2@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"高田史郎",guardiankana:"タカダシロウ",email:"sample-3@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"佐藤武雄",guardiankana:"サトウタケオ",email:"sample-4@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"杉村紀子",guardiankana:"スギムラノリコ",email:"sample-5@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"伊藤七海",guardiankana:"イトウナナミ",email:"sample-6@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"工藤幸子",guardiankana:"クドウサチコ",email:"sample-7@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"斎藤雅美",guardiankana:"サイトウマサミ",email:"sample-8@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"太田祐樹",guardiankana:"オオタユウタ",email:"sample-9@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"古川真由美",guardiankana:"フルカワマユミ",email:"nanoleaf0218@gmail.com",password:"password",password_confirmation:"password")
User.create!(guardian:"上田優",guardiankana:"ウエダユウ",email:"sample-11@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"佐竹真紀",guardiankana:"サタケマキ",email:"sample-12@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"桑田貞",guardiankana:"クワタサダ",email:"sample-13@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"多田千晴",guardiankana:"オオタチハル",email:"sample-14@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"上田優",guardiankana:"ウエダユウ",email:"sample-15@email.com",password:"password",password_confirmation:"password")
User.create!(guardian:"柳生進",guardiankana:"ヤギュウススム",email:"xgppm340@ybb.ne.jp",password:"password",password_confirmation:"password")
User.create!(guardian:"伊藤利典",guardiankana:"イトウトシノリ",email:"tito40358@gmail.com",password:"password",password_confirmation:"password",admin: true)
Student.create!(student_name:"山田良子",studentkana:"ヤマダヨシコ",zoom:false,birthday:"2006/5/15",fix_day:"月",fix_time:"19:10",user_id:2)
Student.create!(student_name:"山田一郎",studentkana:"ヤマダイチロ",zoom:false,birthday:"2010/4/23",fix_day:"火",fix_time:"16:10",user_id:2)
Student.create!(student_name:"山田次郎",studentkana:"ヤマダジロウ",zoom:false,birthday:"2011/4/10",fix_day:"月",fix_time:"16:10",user_id:2)
Student.create!(student_name:"木村花",studentkana:"キムラハナ",zoom:false,birthday:"2006/10/24",fix_day:"火",fix_time:"19:20",user_id:3)
Student.create!(student_name:"高田義男",studentkana:"タカダヨシオ",zoom:false,birthday:"2009/11/24",fix_day:"月",fix_time:"16:25",user_id:4)
Student.create!(student_name:"高田真由",studentkana:"タカダマユ",zoom:false,birthday:"2010/12/24",fix_day:"金",fix_time:"16:30",user_id:4)
Student.create!(student_name:"佐藤良子",studentkana:"サトウヨシコ",zoom:false,birthday:"2004/4/10",fix_day:"月",fix_time:"19:30",user_id:5)
Student.create!(student_name:"佐藤太郎",studentkana:"ヤマダタロウ",zoom:false,birthday:"2010/4/10",fix_day:"金",fix_time:"16:45",user_id:5)
Student.create!(student_name:"杉村都和",studentkana:"スギムラトワ",zoom:false,birthday:"2011/4/10",fix_day:"火",fix_time:"16:10",user_id:6)
Student.create!(student_name:"伊藤千佳",studentkana:"イトウチカ",zoom:true,birthday:"2004/10/24",fix_day:"水",fix_time:"19:05",user_id:7)
Student.create!(student_name:"伊藤裕",studentkana:"イトウヒロシ",zoom:true,birthday:"2009/11/24",fix_day:"火",fix_time:"16:25",user_id:7)
Student.create!(student_name:"工藤沙知",studentkana:"クドウナナ",zoom:false,birthday:"2010/12/24",fix_day:"土",fix_time:"10:30",user_id:8)
Student.create!(student_name:"工藤勉",studentkana:"クドウベン",zoom:false,birthday:"2010/12/24",fix_day:"日",fix_time:"10:30",user_id:8)
Student.create!(student_name:"工藤奈々",studentkana:"クドウナナ",zoom:false,birthday:"2010/12/24",fix_day:"土",fix_time:"10:30",user_id:8)
Student.create!(student_name:"斎藤元気",studentkana:"サイトウゲンキ",zoom:false,birthday:"2005/12/24",fix_day:"日",fix_time:"13:36",user_id:9)
Student.create!(student_name:"斎藤裕子",studentkana:"サイトウユウコ",zoom:false,birthday:"2012/12/24",fix_day:"土",fix_time:"10:30",user_id:9)
Student.create!(student_name:"太田沙",studentkana:"オオタサち",zoom:true,birthday:"2005/12/24",fix_day:"月",fix_time:"19:36",user_id:10)
Student.create!(student_name:"太田仁",studentkana:"オオタジン",zoom:true,birthday:"2012/12/24",fix_day:"土",fix_time:"10:30",user_id:10)
Student.create!(student_name:"古川那奈",studentkana:"フルカワナナ",zoom:false,birthday:"2005/12/10",fix_day:"火",fix_time:"19:36",user_id:11)
Student.create!(student_name:"古川和也",studentkana:"フルカワカズヤ",zoom:false,birthday:"2008/10/02",fix_day:"土",fix_time:"10:30",user_id:11)
Student.create!(student_name:"上田智",studentkana:"ウエダトモ",zoom:false,birthday:"2007/09/24",fix_day:"月",fix_time:"16:36",fix_day2:"金",fix_time2:"16:50",examinee:true,user_id:12)
Student.create!(student_name:"上田仁",studentkana:"ウエダジン",zoom:false,birthday:"2012/12/24",fix_day:"土",fix_time:"10:30",user_id:12)
Student.create!(student_name:"佐竹優",studentkana:"サタケユウ",zoom:false,birthday:"2007/09/24",fix_day:"水",fix_time:"16:36",fix_day2:"金",fix_time2:"16:10",examinee:true,user_id:13)
Student.create!(student_name:"佐竹元気",studentkana:"サタケゲンキ",zoom:false,birthday:"2005/03/24",fix_day:"水",fix_time:"20:30",examinee:true,user_id:13)
Student.create!(student_name:"桑田祐樹",studentkana:"クワタユウキ",zoom:false,birthday:"2009/09/24",fix_day:"木",fix_time:"16:36",user_id:14)
Student.create!(student_name:"多田茂",studentkana:"タダシゲル",zoom:true,birthday:"2005/12/24",fix_day:"木",fix_time:"20:36",user_id:15)
Student.create!(student_name:"多田美玖",studentkana:"タダミク",zoom:false,birthday:"2010/01/24",fix_day:"火",fix_time:"16:56",user_id:15)
Student.create!(student_name:"上田正志",studentkana:"ウエダマサシ",zoom:false,birthday:"2009/05/24",fix_day:"木",fix_time:"16:20",user_id:16)
Student.create!(student_name:"柳生三郎",studentkana:"ヤギュウサブロウ",zoom:true,birthday:"2009/12/24",fix_day:"火",fix_time:"16:15",user_id:17)
Student.create!(student_name:"柳生巴",studentkana:"ヤギュウトモエ",zoom:true,birthday:"2005/05/24",fix_day:"木",fix_time:"19:10",user_id:17)
Student.create!(student_name:"柳生正志",studentkana:"ヤギュウマサシ",zoom:true,birthday:"2010/05/24",fix_day:"金",fix_time:"16:20",user_id:17)
61.times do |n|
  notice_title = "sample-#{n+1}タイトル"
  notice_content = "sample-#{n+1}内容"
  Notice.create!(notice_title: notice_title,
                 notice_content: notice_content,user_id:1)
end
